#%RAML 1.0 DataType
type: object
displayName: Client
properties:
  user_details:
    type: UserDetails
    required: true
  age:
    type: integer
    required: true
  gender:
    type: string
    required: true
  height:
    type: integer
    required: true
  weight:
    type: number
    required: true
