#%RAML 1.0 DataType
type: object
displayName: Meal
properties:
  name:
    type: string
    required: true
    example: "Varske su pienu"
  description:
    type: string
    required: false
    example: "Galima rinktis tarp alma arba valio, pagal skoni"
  meal_number:
    type: integer
    required: true
