#%RAML 1.0 DataType
type: object
displayName: Trainer service request
properties:
  title:
    type: string
    required: true
    example: "Mitybos planas"
  description:
    type: string
    required: false
    example: "Sudaromas vienos dienos mitybos planas specialiai jums"
  price:
    type: number
    required: false
